### ISSUE TITLE
Nixpkgs latest stable is not yet stable

### ISSUE THREAD

**Issue by yajo** [DeterminateSystems/flakehub-mirror#28]
According to https://flakehub.com/flake/NixOS/nixpkgs:

> Get the current stable Nixpkgs
>
>     nix flake show "https://flakehub.com/f/NixOS/nixpkgs/*.tar.gz"

That yields the equivalent to `nixos-24.05` as of today.

However, that isn't yet released as stable: https://github.com/NixOS/nixpkgs/issues/303285

IMHO there should be some way to indicate you want to pin the latest *released* stable NixOS version automatically.

**Comment by tph5595** [comment]
Just checked and it has been pulled from flakehub. This issue should be marked resolved and closed

**Comment by grahamc** [comment]
We have one more issue to resolve, which will prevent it from happening _next_ release :).

**Comment by yajo** [comment]
Thanks!

**Comment by grahamc** [comment]
Ok, this should be solved in a persistent way 👍!

**Comment by yajo** [comment]
Nice, thanks!
