### ISSUE TITLE
poetry2nix tags lagging?

### ISSUE THREAD

**Issue by yajo** [DeterminateSystems/flakehub-mirror#36]
In FH poetry2nix is at 1.28.0.

However, last release is https://github.com/nix-community/poetry2nix/releases/tag/2024.6.2449719

Is it out of sync?

**Comment by cole-h** [comment]
You can find the latest release for poetry2nix here: https://flakehub.com/flake/nix-community/poetry2nix/0.1.3147+rev-46ce1e17d4a97a3cd5bf5433a7afd8d3e09ee106

(and in general, you can visit the releases page to see a list of all releases: https://flakehub.com/flake/nix-community/poetry2nix/releases)

**Comment by yajo** [comment]
Ah... so the versioning is different?

**Comment by cole-h** [comment]
Correct, we give you access to their "rolling releases" as a semver version of `0.1.<number of commits>`.

**Comment by yajo** [comment]
Weird... Their codes are pseudovalid semver already. Anyways it's good enough.
